### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by xAbdaziz** [weirdoshere/ASPIRE5-OC0.6.4-BIGSUR#1]
Hello, My trackpad doesn't work
i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
is that right or maybe i should look into something else?

**Comment by weirdoshere** [comment]
> Hello, My trackpad doesn't work
> i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> is that right or maybe i should look into something else?

its fine

**Comment by xAbdaziz** [comment]
> > Hello, My trackpad doesn't work
> > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > is that right or maybe i should look into something else?
> 
> its fine

You mean it's fine on your side?
or yes i should do what i suggested?

**Comment by weirdoshere** [comment]
> > > Hello, My trackpad doesn't work
> > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > is that right or maybe i should look into something else?
> > 
> > 
> > its fine
> 
> You mean it's fine on your side?
> or yes i should do what i suggested?

i mean its working fine on my side ! 
what is the issue on your side?

**Comment by xAbdaziz** [comment]
> > > > Hello, My trackpad doesn't work
> > > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > > is that right or maybe i should look into something else?
> > > 
> > > 
> > > its fine
> > 
> > 
> > You mean it's fine on your side?
> > or yes i should do what i suggested?
> 
> i mean its working fine on my side !
> what is the issue on your side?

My trackpad doesn't work at all

**Comment by weirdoshere** [comment]
> > > > > Hello, My trackpad doesn't work
> > > > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > > > is that right or maybe i should look into something else?
> > > > 
> > > > 
> > > > its fine
> > > 
> > > 
> > > You mean it's fine on your side?
> > > or yes i should do what i suggested?
> > 
> > 
> > i mean its working fine on my side !
> > what is the issue on your side?
> 
> My trackpad doesn't work at all

is yours the same model?

**Comment by xAbdaziz** [comment]
> > > > > > Hello, My trackpad doesn't work
> > > > > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > > > > is that right or maybe i should look into something else?
> > > > > 
> > > > > 
> > > > > its fine
> > > > 
> > > > 
> > > > You mean it's fine on your side?
> > > > or yes i should do what i suggested?
> > > 
> > > 
> > > i mean its working fine on my side !
> > > what is the issue on your side?
> > 
> > 
> > My trackpad doesn't work at all
> 
> is yours the same model?

Yes, A515-51G with ELAN Trackpad

do i need anything to make it work other than SSDT-I2C.aml and Voodoo Kexts?

**Comment by weirdoshere** [comment]
> > > > > > > Hello, My trackpad doesn't work
> > > > > > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > > > > > is that right or maybe i should look into something else?
> > > > > > 
> > > > > > 
> > > > > > its fine
> > > > > 
> > > > > 
> > > > > You mean it's fine on your side?
> > > > > or yes i should do what i suggested?
> > > > 
> > > > 
> > > > i mean its working fine on my side !
> > > > what is the issue on your side?
> > > 
> > > 
> > > My trackpad doesn't work at all
> > 
> > 
> > is yours the same model?
> 
> Yes, A515-51G with ELAN Trackpad
> 
> do i need anything to make it work other than SSDT-I2C.aml and Voodoo Kexts?

try replacing my voodoo kext(don't downlaod just use mine)
VoodooI2C.kext
VoodooI2CHID.kext
VoodooInput.kext
VoodooPS2Controller.kext

**Comment by xAbdaziz** [comment]
> > > > > > > > Hello, My trackpad doesn't work
> > > > > > > > i took a look on SSDT-I2C.aml and i thought maybe i should change Device name from TPXX to mine (TPAD)
> > > > > > > > is that right or maybe i should look into something else?
> > > > > > > 
> > > > > > > 
> > > > > > > its fine
> > > > > > 
> > > > > > 
> > > > > > You mean it's fine on your side?
> > > > > > or yes i should do what i suggested?
> > > > > 
> > > > > 
> > > > > i mean its working fine on my side !
> > > > > what is the issue on your side?
> > > > 
> > > > 
> > > > My trackpad doesn't work at all
> > > 
> > > 
> > > is yours the same model?
> > 
> > 
> > Yes, A515-51G with ELAN Trackpad
> > do i need anything to make it work other than SSDT-I2C.aml and Voodoo Kexts?
> 
> try replacing my voodoo kext(don't downlaod just use mine)
> VoodooI2C.kext
> VoodooI2CHID.kext
> VoodooInput.kext
> VoodooPS2Controller.kext

Doesn't work

**Comment by xAbdaziz** [comment]
did you use a patch in config.plist to make it work?

**Comment by weirdoshere** [comment]
> did you use a patch in config.plist to make it work?

nope! I dont use any patches
i use only ssdt-i2c.aml,ssdt-ps2k.aml and the above kext once i updated the kext to latest but not working and reverting back to the older versions works like a charm

**Comment by xAbdaziz** [comment]
Fixed it by making Voodoo GPIO load before other Voodoos

**Comment by weirdoshere** [comment]
> Fixed it by making Voodoo GPIO load before other Voodoos

did u manage to fix SD card reader?
and also can u help me with boot chime?

**Comment by xAbdaziz** [comment]
> did u manage to fix SD card reader?
> and also can u help me with boot chime?

i don't have a SD Card so can't test that.
as for the boot chime i still didn't get to that part as i'm still trying to fix other stuff

**Comment by xAbdaziz** [comment]
What's the problem with Boot chime exactly?
